services:
  - type: web
    name: vmach-news
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_NEWS_API_KEY
        sync: false 